services:
  backend:
    build: ./Backend/
    volumes:
      - ./Backend/src:/src
    working_dir: /src
    entrypoint: ["java", "main/HelloWorldMain.java"]
    ports:
      - 8080:80
  #frontend:
  #...
  #nlp:
  #...
