version: "3.9"
services:
  backend:
    build: ./src/backend
    ports:
      - 5000:8080
    secrets:
      - source: here-api-key
  nlp:
    build: ./src/nlp
    volumes:
      - ./src/nlp:/app
    ports:
      - 4000:8000
    command: /app/entrypoint.sh
  frontend:
    build:
      context: ./src/frontend
      args:
        BACKEND_API_ROOT: http://backend:8080/backend
        ENVIRONMENT: development
    ports:
      - 8080:3000
    environment:
      - BACKEND_API_ROOT=http://backend:8080/backend
      - ENVIRONMENT=development
secrets:
  here-api-key:
    file: ./secrets/here-api-key.txt
