services:
  backend:
    build: ./src/backend
    ports:
      - 5000:8080
  nlp:
    build: ./src/nlp
    volumes:
      - ./src/nlp:/src
    ports:
      - 4000:8000
    entrypoint: ["uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
  frontend:
    build:
      context: ./src/frontend
      args:
        NEXT_PUBLIC_BACKEND_API_ROOT: http://localhost:5000/backend/user_query
    ports:
      - 8080:3000
    environment:
      - NEXT_PUBLIC_BACKEND_API_ROOT=http://localhost:5000/backend/user_query
