services:
  backend:
    build: ./src/backend
    volumes:
      - ./src/backend:/src
    working_dir: /src
    entrypoint: ["java", "main/HelloWorldMain.java"]
  nlp:
    build: ./src/nlp
    volumes:
      - ./src/nlp:/src
  frontend:
    build: 
      context: ./src/frontend
      args:
        NEXT_PUBLIC_BACKEND_API_ROOT: http://backend:5000
    ports:
      - 8080:3000
    environment:
      - NEXT_PUBLIC_BACKEND_API_ROOT=http://backend:5000