services:
  backend:
    build: ./src/backend
    volumes:
      - ./src/backend:/src
    working_dir: /src
#    entrypoint: ["java", "main/java/com/geodatasearch/backend/BackendApplication.java"]
#    entrypoint: "/bin/sh"
#    command: "/bin/sh"
    ports:
      - 5000:5000
  nlp:
    build: ./src/nlp
    volumes:
      - ./src/nlp:/src
  frontend:
    build: ./src/frontend
    ports:
      - 8080:3000
