version: "3"
services:
  backend:
    build: ./src/backend
    ports:
      - 5000:8080
  nlp:
    build: ./src/nlp
    volumes:
      - ./src/nlp:/app
    ports:
      - 4000:8000
    entrypoint: /app/entrypoint.sh
  frontend:
    build:
      context: ./src/frontend
      args:
        BACKEND_API_ROOT: http://backend:8080/backend
        ENVIRONMENT: development
    ports:
      - 8080:3000
    environment:
      - BACKEND_API_ROOT=http://backend:8080/backend
      - ENVIRONMENT=development
