services:
  backend:
    build: ./src/backend
    volumes:
      - ./src/backend:/src
    working_dir: /src
    ports:
      - 5000:8080
  nlp:
    build: ./src/nlp
    volumes:
      - ./src/nlp:/src
  frontend:
    build:
      context: ./src/frontend
      args:
        NEXT_PUBLIC_BACKEND_API_ROOT: http://localhost:5000/backend/user_query
    ports:
      - 8080:3000
    environment:
      - NEXT_PUBLIC_BACKEND_API_ROOT=http://localhost:5000/backend/user_query
