services:
  backend:
    build: ./src/backend
    volumes:
      - ./src/backend:/src
    working_dir: /src
    entrypoint: ["java", "main/HelloWorldMain.java"]
    ports:
      - 8080:80
  nlp:
    build: ./src/nlp
    volumes:
      - ./src/nlp:/src
  #frontend:
  #...
