# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Backend tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_n_run:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v2
      - name: check the docker version
        run: docker version
      - name: prepare dummy key file
        run: touch secrets/here-api-key.txt
      - name: build backend
        run: docker compose up -d --build backend
      - name: list running containers
        run: docker ps
      - name: wait 5 seconds
        run: sleep 5
      - name: check the current directory
        run: ls -la
#      - name: check the container is still running
#        run: docker compose exec backend "which echo"
  tests:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v2
      - name: run tests
        run: docker build --target maven_test -f src/backend/Dockerfile src/backend
